# Generated by Django 4.1 on 2023-08-25 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(max_length=200, verbose_name='должность')),
                ('entry_date', models.DateField(verbose_name='дата приема на работу')),
                ('salary', models.IntegerField(verbose_name='зарплата')),
                ('level', models.CharField(max_length=200, verbose_name='иерархический уровень')),
                ('boss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='app.employee', verbose_name='кто начальник')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'db_table': 'employee',
            },
        ),
    ]
