# Generated by Django 4.1 on 2023-08-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_employee_boss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='middlemanager',
            name='boss',
        ),
        migrations.RemoveField(
            model_name='topmanager',
            name='boss',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='boss',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='level',
        ),
        migrations.DeleteModel(
            name='Foreman',
        ),
        migrations.DeleteModel(
            name='GeneralManager',
        ),
        migrations.DeleteModel(
            name='MiddleManager',
        ),
        migrations.DeleteModel(
            name='TopManager',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
